Repository WebDevJBR/volunteer-points-log, pull requests merged in 2020-01, with the labels that each got.

#5 ISSUE #3 | Add debug config
  .vscode/launch.json
  nodemon.json
  ormconfig.json
  package.json
Labels: enhancement

#9 Create nodejs.yml
  .github/workflows/nodejs.yml
  README.md
Labels: enhancement

#11 ISSUE #6 | Update README.md
  README.md
Labels: documentation

#12 ISSUE #10 | Fix TypeORM config, move database.db, adjust other configs.
  .vscode/launch.json
  db/database.db
  ormconfig.json
  package.json
Labels: bug

#34 ISSUE #15 | Add landing page
  .github/workflows/nodejs.yml
  .vscode/launch.json
  client/@types/scss.d.ts
  client/package-lock.json
  client/package.json
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/Landing/Landing.module.scss
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/AdminLogin/AdminLogin.tsx
  client/src/components/Login/UserLogin/UserLogin.tsx
  client/src/hoc/Layout/Layout.module.scss
  client/src/hoc/Layout/Layout.tsx
  client/src/routes.tsx
  client/src/shared/Input/Button/Button.tsx
  client/src/shared/Input/Search/SearchBox.tsx
  client/tsconfig.json
Labels: enhancement

#36 ISSUE #14 | Add user login page
  client/src/components/Login/AdminLogin/AdminLogin.module.scss
  client/src/components/Login/UserLogin/UserLogin.module.scss
  client/src/components/Login/UserLogin/UserLogin.tsx
  client/src/shared/Input/Button/Button.module.scss
  client/src/shared/Input/Button/Button.tsx
  client/src/shared/Input/Search/SearchBox.module.scss
  client/src/shared/Interfaces/IUser.ts
  client/src/variables.scss
Labels: enhancement

#39 Config
  .vscode/launch.json
  nodemon.json
  package.json
Labels: enhancement

#37 Features/issue 33
  client/package-lock.json
  client/package.json
  client/src/components/Login/UserLogin/UserLogin.tsx
  client/src/shared/Services/ApiService.ts
  db/database.db
  server/constants/HttpStatusCodes.ts
  server/controller/UserController.ts
  server/controller/VolunteerController.ts
  server/routes.ts
  server/server.ts
Labels: enhancement
