Repository WebDevJBR/volunteer-points-log, pull requests merged in 2020-02, with the labels that each got.

#42 Completing ApiService, which fulfills #33
  client/src/components/Login/UserLogin/UserLogin.tsx
  client/src/shared/Services/ApiService.ts
Labels: enhancement

#47 ISSUE #13 | Add admin login page
  client/package.json
  client/src/components/Landing/Landing.module.scss
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/AdminLogin/AdminLogin.module.scss
  client/src/components/Login/AdminLogin/AdminLogin.tsx
  client/src/components/Login/Login.module.scss
  client/src/components/Login/Login.tsx
  client/src/components/Login/UserLogin/UserLogin.module.scss
  client/src/components/Login/UserLogin/UserLogin.tsx
  client/src/shared/Input/Button/Button.tsx
  client/src/shared/Input/TextField/TextField.module.scss
  client/src/shared/Input/TextField/TextField.tsx
  client/src/variables.scss
Labels: enhancement

#50 ISSUE #48 | Add global snackbar
  client/src/components/Landing/Landing.tsx
  client/src/components/Login/AdminLogin/AdminLogin.tsx
  client/src/components/Login/UserLogin/UserLogin.tsx
  client/src/components/Register/AddUser/AddUser.tsx
  client/src/hoc/Layout/Layout.tsx
  client/src/index.tsx
  client/src/shared/Constants/Api/ApiEndpoints.ts
  client/src/shared/Constants/index.ts
  client/src/shared/Input/Button/Button.tsx
  client/src/shared/Input/index.ts
  client/src/shared/Interfaces/IUser.ts
  client/src/shared/Interfaces/User/IUser.ts
  client/src/shared/Interfaces/index.ts
  client/src/shared/Services/Api/ApiService.ts
  client/src/shared/Services/index.ts
  client/src/store/Actions/Snackbar/index.ts
  client/src/store/Actions/Types/Snackbar/index.ts
  client/src/store/Actions/Types/index.ts
  client/src/store/Actions/index.ts
  client/src/store/Interfaces/Snackbar/index.ts
  client/src/store/Interfaces/index.ts
  client/src/store/Reducers/Snackbar/index.tsx
  client/src/store/Reducers/index.ts
  client/src/store/index.tsx
  db/database.db
Labels: enhancement

#55 ISSUE #54 | Change Landing to Login
  client/src/components/Login/Login.module.scss
  client/src/components/Login/Login.tsx
  client/src/routes.tsx
Labels: enhancement

#52 Features/issue 49
  server/constants/HttpStatusCodes.ts
  server/controller/DepartmentController.ts
  server/controller/KingdomController.ts
  server/controller/LocalGroupController.ts
  server/controller/UserController.ts
  server/controller/VolunteerController.ts
  server/routes.ts
Labels: enhancement

#59 add prettier config file & remove from gitignore
  .gitignore
  .prettierrc
Labels: enhancement

#58 ISSUE #17 | Add admin landing page.
  client/package-lock.json
  client/package.json
  client/src/components/Landing/AdminLanding/AdminLanding.module.scss
  client/src/components/Landing/AdminLanding/AdminLanding.tsx
  client/src/components/Landing/AdminLanding/DataManagement/DataManagement.tsx
  client/src/components/Landing/AdminLanding/DataManagement/DateConfig/DateConfig.module.scss
  client/src/components/Landing/AdminLanding/DataManagement/DateConfig/DateConfig.tsx
  client/src/components/Landing/AdminLanding/DataManagement/Departments/Departments.module.scss
  client/src/components/Landing/AdminLanding/DataManagement/Departments/Departments.tsx
  client/src/components/Landing/AdminLanding/DataManagement/Kingdoms/Kingdoms.module.scss
  client/src/components/Landing/AdminLanding/DataManagement/Kingdoms/Kingdoms.tsx
  client/src/components/Landing/AdminLanding/DataManagement/LocalGroups/LocalGroups.module.scss
  client/src/components/Landing/AdminLanding/DataManagement/LocalGroups/LocalGroups.tsx
  client/src/components/Landing/AdminLanding/ImportExport/ImportExport.tsx
  client/src/routes.tsx
  client/src/shared/Input/Select/Select.tsx
  client/src/shared/Input/TextField/TextField.tsx
Labels: enhancement

#67 ISSUE #29 | Adds volunteer cards for the user landing page
  client/src/assets/yellow-crown.png
  client/src/components/Landing/UserLanding/UserLanding.module.scss
  client/src/components/Landing/UserLanding/UserLanding.tsx
  client/src/components/Landing/UserLanding/VolunteerCard/VolunteerCard.module.scss
  client/src/components/Landing/UserLanding/VolunteerCard/VolunteerCard.tsx
  client/src/routes.tsx
  client/src/shared/Input/Search/SearchBox.tsx
  package-lock.json
  package.json
Labels: enhancement

#68 ISSUE #31 | Adds support for docker
  .dockerignore
  Dockerfile
Labels: enhancement, research

#65 ISSUE #64 | Fix some endpoint issues.
  server/controller/DepartmentController.ts
  server/controller/KingdomController.ts
  server/controller/LocalGroupController.ts
  server/controller/UserController.ts
  server/controller/VolunteerController.ts
  server/entity/LocalGroup.ts
  server/routes.ts
Labels: bug

#62 ISSUE #30 | Add volunteer hours page.
  client/src/components/Edit/VolunteerHours/VolunteerHours.module.scss
  client/src/components/Edit/VolunteerHours/VolunteerHours.tsx
  client/src/routes.tsx
Labels: enhancement

#73 Issue #70, Issue #71 | Implement DateRange table and DateRangeController
  server/controller/DateRangeController.ts
  server/entity/DateRange.ts
  server/routes.ts
Labels: enhancement

#75 Issue #74 | modify update endpoints to use TypeORM update method instead of save
  server/controller/DepartmentController.ts
  server/controller/KingdomController.ts
  server/controller/LocalGroupController.ts
  server/controller/VolunteerController.ts
Labels: bug

#69 Features/time entry controller
  server/controller/VolunteerTimeEntryController.ts
  server/routes.ts
Labels: enhancement

#76 ISSUE #72 | Implement backend for Admin Data Management
  .vscode/launch.json
  client/src/components/Landing/AdminLanding/DataManagement/Departments/Departments.tsx
  client/src/components/Landing/AdminLanding/DataManagement/Kingdoms/Kingdoms.tsx
  client/src/components/Landing/AdminLanding/DataManagement/LocalGroups/LocalGroups.tsx
  client/src/hoc/Layout/Layout.tsx
  client/src/shared/Input/Select/Select.tsx
  client/src/shared/Interfaces/Select/ISelect.ts
  db/database.db
  package.json
  server/controller/DepartmentController.ts
  server/controller/KingdomController.ts
  server/controller/LocalGroupController.ts
  server/routes.ts
  server/server.ts
Labels: enhancement
